# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins: [jekyll-paginate,jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            AIML Seminar @ UVa
tagline:          ''
description:      'The Weekly Artificial Intelligence and Machine Learning Seminar in UVa'
url:              http://uvaml.github.io
baseurl:          ""
# baseurl:	  http://127.0.0.1:4000

author:
  name:           'Yangfeng Ji'
  url:            https://yangfengji.net

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/uvaml.github.io
